### PR TITLE
Allow for HTTPS Proxy Agent

### LINKED ISSUE #15: Disable certificate verification
**Issue Overview**
When running this code within enterprise network, i get the following error:
failed, reason: self signed certificate in certificate chain

**Steps To Reproduce**
Attempt export of Botmock project within corporate network.

**Expected Behavior**
Expect to export project per instructions.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Win 10
 - NPM Version: 10.15.3

**Additional Context**
We are able to run again the API using Postman, which allows SSL certificate verification to be turned off, so assuming this is the issue.

### PR DESCRIPTION
**Pull request by nonnontrivial**
Resolves #15 
This PR uses the latest version of `@botmock-api/client` which allows for custom `subdomain` and `shouldRejectUnauthorized` to be passed to the inner HTTP client.

## Usage

The script can now (optionally) accept `process.env.SUBDOMAIN` and `process.env.SHOULD_REJECT_UNAUTHORIZED`.

```console
SUBDOMAIN="ww2"
SHOULD_REJECT_UNAUTHORIZED="false"
```

### CODE REVIEW

**Comment by mpeaybiz** [comment]
When running with:
SUBDOMAIN="ww2"
SHOULD_REJECT_UNAUTHORIZED="false"

Seeing this error: SyntaxError: Unexpected token w in JSON at position 0
    at JSON.parse (<anonymous>)
    at main (C:\Users\xxx\Documents\GitHub\botmock-lex-export-http-agent\index.ts:35:12)

**Comment by nonnontrivial** [comment]
Can you `git pull origin http-agent` and try again @mpeaybiz ?

**Comment by mpeaybiz** [comment]
Seeing this error (redacted) on this version:

> [2020-03-10T17:53:15.332Z] creating output directories
> [2020-03-10T17:53:15.341Z] fetching project data
> [2020-03-10T17:53:15.599Z] FetchError: request to https://ww2.botmock.com/api/teams/@xxx/projects/@xxx-removed-xxx/variables failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\xxx\Documents\GitHub\botmock-lex-export-http-agent\node_modules\node-fetch\lib\index.js:1455:11)

**Comment by nonnontrivial** [comment]
@mpeaybiz what version of node are you running?

**Comment by mpeaybiz** [comment]
It is the version that I cloned  from the branch after the last change. Files matche changes from commits: https://github.com/Botmock/botmock-lex-export/pull/16/files

I'm not that good with Git... is there a way in Visual Studio Code to display code version?

**Comment by nonnontrivial** [comment]
@mpeaybiz you can select (in the Visual Studio Code menu)`Terminal` > `New Terminal` and then run `node --version`.

**Comment by mpeaybiz** [comment]
Here is the output:

PS C:\Users\user\Documents\GitHub\botmock-lex-export-http-agent> node --version
v10.15.3

**Comment by nonnontrivial** [comment]
@mpeaybiz can you try downloading the latest LTS version here? https://nodejs.org/en/

**Comment by mpeaybiz** [comment]
I will need to investigate over the next days if this can be installed on my company laptop. It may be locked down to Node 10.15.3. I will respond with an update.

Thank you,
Matt

**Comment by mpeaybiz** [comment]
Hi Kevin, we're seeing the same error with node 12.14.1. This is the latest version we are authorized to use within out enterprise.

Params in .env file, have changed the token and IDs for security:

BOTMOCK_TOKEN=@adsfadfasdfasdfsdf
BOTMOCK_TEAM_ID=@12345
BOTMOCK_PROJECT_ID=@asfasdfsdafasdf
BOTMOCK_BOARD_ID=@adsfasdfasdfsdf
NODE_TLS_REJECT_UNAUTHORIZED=0
SUBDOMAIN=ww2
SHOULD_REJECT_UNAUTHORIZED=false

[cid:image001.jpg@01D5F853.A13D70B0]



Public Information
From: Pearce, Matthew
Sent: Wednesday, March 11, 2020 7:40 AM
To: Botmock/botmock-lex-export <reply@reply.github.com>; Botmock/botmock-lex-export <botmock-lex-export@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [External] Re: [Botmock/botmock-lex-export] Configure client for rejecting unauthorized (#16)

I will need to investigate over the next days if this can be installed on my company laptop. It may be locked down to Node 10.15.3. I will respond with an update.

Thank you,
Matt

**Comment by mpeaybiz** [comment]
FYI... we are able to run other such tools by setting a proxy server name and port. Is it possible to specify those parameters?



Public Information
From: Pearce, Matthew
Sent: Thursday, March 12, 2020 9:50 AM
To: Botmock/botmock-lex-export <reply@reply.github.com>; Botmock/botmock-lex-export <botmock-lex-export@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Henry, Clarence <chenu@allstate.com>
Subject: RE: [External] Re: [Botmock/botmock-lex-export] Configure client for rejecting unauthorized (#16)

Hi Kevin, we're seeing the same error with node 12.14.1. This is the latest version we are authorized to use within out enterprise.

Params in .env file, have changed the token and IDs for security:

BOTMOCK_TOKEN=@adsfadfasdfasdfsdf
BOTMOCK_TEAM_ID=@12345
BOTMOCK_PROJECT_ID=@asfasdfsdafasdf
BOTMOCK_BOARD_ID=@adsfasdfasdfsdf
NODE_TLS_REJECT_UNAUTHORIZED=0
SUBDOMAIN=ww2
SHOULD_REJECT_UNAUTHORIZED=false

[cid:image001.jpg@01D5F853.A13D70B0]



Public Information
From: Pearce, Matthew
Sent: Wednesday, March 11, 2020 7:40 AM
To: Botmock/botmock-lex-export <reply@reply.github.com<mailto:reply@reply.github.com>>; Botmock/botmock-lex-export <botmock-lex-export@noreply.github.com<mailto:botmock-lex-export@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [External] Re: [Botmock/botmock-lex-export] Configure client for rejecting unauthorized (#16)

I will need to investigate over the next days if this can be installed on my company laptop. It may be locked down to Node 10.15.3. I will respond with an update.

Thank you,
Matt

**Comment by mpeaybiz** [comment]
Hi Kevin, just wanted to follow up on this item...

Thanks,
Matt



Public Information
From: Pearce, Matthew
Sent: Thursday, March 12, 2020 9:50 AM
To: Botmock/botmock-lex-export <reply@reply.github.com>; Botmock/botmock-lex-export <botmock-lex-export@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Henry, Clarence <chenu@allstate.com>
Subject: RE: [External] Re: [Botmock/botmock-lex-export] Configure client for rejecting unauthorized (#16)

Hi Kevin, we're seeing the same error with node 12.14.1. This is the latest version we are authorized to use within out enterprise.

Params in .env file, have changed the token and IDs for security:

BOTMOCK_TOKEN=@adsfadfasdfasdfsdf
BOTMOCK_TEAM_ID=@12345
BOTMOCK_PROJECT_ID=@asfasdfsdafasdf
BOTMOCK_BOARD_ID=@adsfasdfasdfsdf
NODE_TLS_REJECT_UNAUTHORIZED=0
SUBDOMAIN=ww2
SHOULD_REJECT_UNAUTHORIZED=false

[cid:image001.jpg@01D5F853.A13D70B0]



Public Information
From: Pearce, Matthew
Sent: Wednesday, March 11, 2020 7:40 AM
To: Botmock/botmock-lex-export <reply@reply.github.com<mailto:reply@reply.github.com>>; Botmock/botmock-lex-export <botmock-lex-export@noreply.github.com<mailto:botmock-lex-export@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [External] Re: [Botmock/botmock-lex-export] Configure client for rejecting unauthorized (#16)

I will need to investigate over the next days if this can be installed on my company laptop. It may be locked down to Node 10.15.3. I will respond with an update.

Thank you,
Matt

**Comment by nonnontrivial** [comment]
Hey @mpeaybiz, apologies for the delay.

This is indeed something we can do which will be a subject of a very near future PR which I will link to here.

**Comment by nonnontrivial** [comment]
@mpeaybiz can you `git pull origin http-agent` and provide in your `.env`

```console
HTTP_PROXY=http://some.address:some_port
```

**Pull request closed without merging**
